# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13cdd36e6b2cd1d503dbb983f2e447c51ccc103adc4b7082f144e4109656fcb0a37ee9c791158ca35a7477a312cdd24b409fced107e5d7f5b86f3d61bb9267a3

test:
  secret_key_base: ecb38e45f5ca729ae847234b3c1d2e967537b7c08f0b8e862d1dd2317f5e71e77bcebc6f4541233c266fc3c40802494a487f9b591f2cbd57367cafb17b99be1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
